<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Customize\Controller\AddManagementScreenRoutingController' shared autowired service.

include_once $this->targetDirs[3].'/app/Customize/Controller/AddManagementScreenRoutingController.php';

return $this->services['Customize\\Controller\\AddManagementScreenRoutingController'] = new \Customize\Controller\AddManagementScreenRoutingController();
