<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Customize\Controller\AddAServiceWithoutAbstractClassController' shared autowired service.

include_once $this->targetDirs[3].'/app/Customize/Controller/AddAServiceWithoutAbstractClassController.php';

return $this->services['Customize\\Controller\\AddAServiceWithoutAbstractClassController'] = new \Customize\Controller\AddAServiceWithoutAbstractClassController(${($_ = isset($this->services['Eccube\\Repository\\BaseInfoRepository']) ? $this->services['Eccube\\Repository\\BaseInfoRepository'] : $this->getBaseInfoRepositoryService()) && false ?: '_'});
