<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Customize\Controller\Demo1Controller' shared autowired service.

include_once $this->targetDirs[3].'/app/Customize/Controller/Demo1Controller.php';

return $this->services['Customize\\Controller\\Demo1Controller'] = new \Customize\Controller\Demo1Controller();
