<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Customize\Controller\OverwriteExistRoutingController' shared autowired service.

include_once $this->targetDirs[3].'/app/Customize/Controller/OverwriteExistRoutingController.php';

return $this->services['Customize\\Controller\\OverwriteExistRoutingController'] = new \Customize\Controller\OverwriteExistRoutingController();
