<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container772otna\EccubeDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container772otna/EccubeDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container772otna.legacy');

    return;
}

if (!\class_exists(EccubeDevDebugProjectContainer::class, false)) {
    \class_alias(\Container772otna\EccubeDevDebugProjectContainer::class, EccubeDevDebugProjectContainer::class, false);
}

return new \Container772otna\EccubeDevDebugProjectContainer([
    'container.build_hash' => '772otna',
    'container.build_id' => 'e03301f9',
    'container.build_time' => 1599210322,
], __DIR__.\DIRECTORY_SEPARATOR.'Container772otna');
